// -------------------------------------------------------------
//
// Module: cic_decimate_64
// Generated by MATLAB(R) 9.13 and Filter Design HDL Coder 3.1.12.
// Generated on: 2023-10-11 15:17:24
// -------------------------------------------------------------

// -------------------------------------------------------------
// HDL Code Generation Options:
//
// ResetType: Synchronous
// OptimizeForHDL: on
// ResetInputPort: rstn
// TargetDirectory: C:\Users\kustin\kustin\metaAtom\matlab
// AddPipelineRegisters: on
// Name: cic_decimate_64
// ResetAssertedLevel: Active-low
// TargetLanguage: Verilog
// TestBenchName: tb_cic_decimate_64
// TestBenchStimulus: step ramp chirp noise 

// -------------------------------------------------------------
// HDL Implementation    : Fully parallel
// -------------------------------------------------------------
// Filter Settings:
//
// Discrete-Time FIR Multirate Filter (real)
// -----------------------------------------
// Filter Structure        : Cascaded Integrator-Comb Decimator
// Decimation Factor       : 64
// Differential Delay      : 1
// Number of Sections      : 4
// Stable                  : Yes
// Linear Phase            : Yes (Type 1)
//
// Input                   : s2,1
// Output                  : s26,1
// Filter Internals        : Full Precision
//   Integrator Section 1  : s26,1
//   Integrator Section 2  : s26,1
//   Integrator Section 3  : s26,1
//   Integrator Section 4  : s26,1
//   Comb Section 1        : s26,1
//   Comb Section 2        : s26,1
//   Comb Section 3        : s26,1
//   Comb Section 4        : s26,1
// -------------------------------------------------------------




`timescale 1 ns / 1 ns

module cic_decimate_64
               (
                clk,
                clk_enable,
                rstn,
                filter_in,
                filter_out,
                ce_out
                );

  input   clk; 
  input   clk_enable; 
  input   rstn; 
  input   signed [1:0] filter_in; //sfix2_En1
  output  signed [25:0] filter_out; //sfix26_En1
  output  ce_out; 

////////////////////////////////////////////////////////////////
//Module Architecture: cic_decimate_64
////////////////////////////////////////////////////////////////
  // Local Functions
  // Type Definitions
  // Constants
  // Signals
  reg  [5:0] cur_count; // ufix6
  wire phase_1; // boolean
  wire ce_delayline; // boolean
  reg  int_delay_pipe [0:2] ; // boolean
  wire ce_gated; // boolean
  reg  ce_out_reg; // boolean
  //   
  reg  signed [1:0] input_register; // sfix2_En1
  //   -- Section 1 Signals 
  wire signed [1:0] section_in1; // sfix2_En1
  wire signed [25:0] section_cast1; // sfix26_En1
  wire signed [25:0] sum1; // sfix26_En1
  reg  signed [25:0] section_out1; // sfix26_En1
  wire signed [25:0] add_cast; // sfix26_En1
  wire signed [25:0] add_cast_1; // sfix26_En1
  wire signed [26:0] add_temp; // sfix27_En1
  //   -- Section 2 Signals 
  wire signed [25:0] section_in2; // sfix26_En1
  wire signed [25:0] sum2; // sfix26_En1
  reg  signed [25:0] section_out2; // sfix26_En1
  wire signed [25:0] add_cast_2; // sfix26_En1
  wire signed [25:0] add_cast_3; // sfix26_En1
  wire signed [26:0] add_temp_1; // sfix27_En1
  //   -- Section 3 Signals 
  wire signed [25:0] section_in3; // sfix26_En1
  wire signed [25:0] sum3; // sfix26_En1
  reg  signed [25:0] section_out3; // sfix26_En1
  wire signed [25:0] add_cast_4; // sfix26_En1
  wire signed [25:0] add_cast_5; // sfix26_En1
  wire signed [26:0] add_temp_2; // sfix27_En1
  //   -- Section 4 Signals 
  wire signed [25:0] section_in4; // sfix26_En1
  wire signed [25:0] sum4; // sfix26_En1
  reg  signed [25:0] section_out4; // sfix26_En1
  wire signed [25:0] add_cast_6; // sfix26_En1
  wire signed [25:0] add_cast_7; // sfix26_En1
  wire signed [26:0] add_temp_3; // sfix27_En1
  //   -- Section 5 Signals 
  wire signed [25:0] section_in5; // sfix26_En1
  reg  signed [25:0] diff1; // sfix26_En1
  wire signed [25:0] section_out5; // sfix26_En1
  wire signed [25:0] sub_cast; // sfix26_En1
  wire signed [25:0] sub_cast_1; // sfix26_En1
  wire signed [26:0] sub_temp; // sfix27_En1
  reg  signed [25:0] cic_pipeline5; // sfix26_En1
  //   -- Section 6 Signals 
  wire signed [25:0] section_in6; // sfix26_En1
  reg  signed [25:0] diff2; // sfix26_En1
  wire signed [25:0] section_out6; // sfix26_En1
  wire signed [25:0] sub_cast_2; // sfix26_En1
  wire signed [25:0] sub_cast_3; // sfix26_En1
  wire signed [26:0] sub_temp_1; // sfix27_En1
  reg  signed [25:0] cic_pipeline6; // sfix26_En1
  //   -- Section 7 Signals 
  wire signed [25:0] section_in7; // sfix26_En1
  reg  signed [25:0] diff3; // sfix26_En1
  wire signed [25:0] section_out7; // sfix26_En1
  wire signed [25:0] sub_cast_4; // sfix26_En1
  wire signed [25:0] sub_cast_5; // sfix26_En1
  wire signed [26:0] sub_temp_2; // sfix27_En1
  reg  signed [25:0] cic_pipeline7; // sfix26_En1
  //   -- Section 8 Signals 
  wire signed [25:0] section_in8; // sfix26_En1
  reg  signed [25:0] diff4; // sfix26_En1
  wire signed [25:0] section_out8; // sfix26_En1
  wire signed [25:0] sub_cast_6; // sfix26_En1
  wire signed [25:0] sub_cast_7; // sfix26_En1
  wire signed [26:0] sub_temp_3; // sfix27_En1
  //   
  reg  signed [25:0] output_register; // sfix26_En1

  // Block Statements
  //   ------------------ CE Output Generation ------------------

  always @ (posedge clk)
    begin: ce_output
      if (rstn == 1'b0) begin
        cur_count <= 6'b000000;
      end
      else begin
        if (clk_enable == 1'b1) begin
          if (cur_count >= 6'b111111) begin
            cur_count <= 6'b000000;
          end
          else begin
            cur_count <= cur_count + 6'b000001;
          end
        end
      end
    end // ce_output

  assign  phase_1 = (cur_count == 6'b000001 && clk_enable == 1'b1) ? 1'b1 : 1'b0;

  always @ (posedge clk)
    begin: ce_delay
      if (rstn == 1'b0) begin
        int_delay_pipe[0] <= 1'b0;
        int_delay_pipe[1] <= 1'b0;
        int_delay_pipe[2] <= 1'b0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          int_delay_pipe[1] <= int_delay_pipe[0];
          int_delay_pipe[2] <= int_delay_pipe[1];
          int_delay_pipe[0] <= clk_enable;
        end
      end
    end // ce_delay
  assign ce_delayline = int_delay_pipe[2];

  assign ce_gated =  ce_delayline & phase_1;

  //   ------------------ CE Output Register ------------------

  always @ ( posedge clk)
    begin: ce_output_register
      if (rstn == 1'b0) begin
        ce_out_reg <= 1'b0;
      end
      else begin
          ce_out_reg <= ce_gated;
      end
    end // ce_output_register

  //   ------------------ Input Register ------------------

  always @ ( posedge clk)
    begin: input_reg_process
      if (rstn == 1'b0) begin
        input_register <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          input_register <= filter_in;
        end
      end
    end // input_reg_process

  //   ------------------ Section # 1 : Integrator ------------------

  assign section_in1 = input_register;

  assign section_cast1 = $signed({{24{section_in1[1]}}, section_in1});

  assign add_cast = section_cast1;
  assign add_cast_1 = section_out1;
  assign add_temp = add_cast + add_cast_1;
  assign sum1 = add_temp[25:0];

  always @ ( posedge clk)
    begin: integrator_delay_section1
      if (rstn == 1'b0) begin
        section_out1 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out1 <= sum1;
        end
      end
    end // integrator_delay_section1

  //   ------------------ Section # 2 : Integrator ------------------

  assign section_in2 = section_out1;

  assign add_cast_2 = section_in2;
  assign add_cast_3 = section_out2;
  assign add_temp_1 = add_cast_2 + add_cast_3;
  assign sum2 = add_temp_1[25:0];

  always @ ( posedge clk)
    begin: integrator_delay_section2
      if (rstn == 1'b0) begin
        section_out2 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out2 <= sum2;
        end
      end
    end // integrator_delay_section2

  //   ------------------ Section # 3 : Integrator ------------------

  assign section_in3 = section_out2;

  assign add_cast_4 = section_in3;
  assign add_cast_5 = section_out3;
  assign add_temp_2 = add_cast_4 + add_cast_5;
  assign sum3 = add_temp_2[25:0];

  always @ ( posedge clk)
    begin: integrator_delay_section3
      if (rstn == 1'b0) begin
        section_out3 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out3 <= sum3;
        end
      end
    end // integrator_delay_section3

  //   ------------------ Section # 4 : Integrator ------------------

  assign section_in4 = section_out3;

  assign add_cast_6 = section_in4;
  assign add_cast_7 = section_out4;
  assign add_temp_3 = add_cast_6 + add_cast_7;
  assign sum4 = add_temp_3[25:0];

  always @ ( posedge clk)
    begin: integrator_delay_section4
      if (rstn == 1'b0) begin
        section_out4 <= 0;
      end
      else begin
        if (clk_enable == 1'b1) begin
          section_out4 <= sum4;
        end
      end
    end // integrator_delay_section4

  //   ------------------ Section # 5 : Comb ------------------

  assign section_in5 = section_out4;

  assign sub_cast = section_in5;
  assign sub_cast_1 = diff1;
  assign sub_temp = sub_cast - sub_cast_1;
  assign section_out5 = sub_temp[25:0];

  always @ ( posedge clk)
    begin: comb_delay_section5
      if (rstn == 1'b0) begin
        diff1 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff1 <= section_in5;
        end
      end
    end // comb_delay_section5

  always @ ( posedge clk)
    begin: cic_pipeline_process_section5
      if (rstn == 1'b0) begin
        cic_pipeline5 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          cic_pipeline5 <= section_out5;
        end
      end
    end // cic_pipeline_process_section5

  //   ------------------ Section # 6 : Comb ------------------

  assign section_in6 = cic_pipeline5;

  assign sub_cast_2 = section_in6;
  assign sub_cast_3 = diff2;
  assign sub_temp_1 = sub_cast_2 - sub_cast_3;
  assign section_out6 = sub_temp_1[25:0];

  always @ ( posedge clk)
    begin: comb_delay_section6
      if (rstn == 1'b0) begin
        diff2 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff2 <= section_in6;
        end
      end
    end // comb_delay_section6

  always @ ( posedge clk)
    begin: cic_pipeline_process_section6
      if (rstn == 1'b0) begin
        cic_pipeline6 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          cic_pipeline6 <= section_out6;
        end
      end
    end // cic_pipeline_process_section6

  //   ------------------ Section # 7 : Comb ------------------

  assign section_in7 = cic_pipeline6;

  assign sub_cast_4 = section_in7;
  assign sub_cast_5 = diff3;
  assign sub_temp_2 = sub_cast_4 - sub_cast_5;
  assign section_out7 = sub_temp_2[25:0];

  always @ ( posedge clk)
    begin: comb_delay_section7
      if (rstn == 1'b0) begin
        diff3 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff3 <= section_in7;
        end
      end
    end // comb_delay_section7

  always @ ( posedge clk)
    begin: cic_pipeline_process_section7
      if (rstn == 1'b0) begin
        cic_pipeline7 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          cic_pipeline7 <= section_out7;
        end
      end
    end // cic_pipeline_process_section7

  //   ------------------ Section # 8 : Comb ------------------

  assign section_in8 = cic_pipeline7;

  assign sub_cast_6 = section_in8;
  assign sub_cast_7 = diff4;
  assign sub_temp_3 = sub_cast_6 - sub_cast_7;
  assign section_out8 = sub_temp_3[25:0];

  always @ ( posedge clk)
    begin: comb_delay_section8
      if (rstn == 1'b0) begin
        diff4 <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          diff4 <= section_in8;
        end
      end
    end // comb_delay_section8

  //   ------------------ Output Register ------------------

  always @ ( posedge clk)
    begin: output_reg_process
      if (rstn == 1'b0) begin
        output_register <= 0;
      end
      else begin
        if (phase_1 == 1'b1) begin
          output_register <= section_out8;
        end
      end
    end // output_reg_process

  // Assignment Statements
  assign ce_out = ce_out_reg;
  assign filter_out = output_register;
endmodule  // cic_decimate_64
